apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: controller
  namespace: argocd
spec:
  project: controller
  source:
    repoURL: https://github.com/richamishra006/argocd-test.git
    targetRevision: HEAD
    path: controller
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
