apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/richamishra006/argocd-test.git
    targetRevision: HEAD
    path: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: default
