apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
        command: ["/bin/sh", "-c"]
        args:
        - >
          cp /usr/share/nginx/html/index.html /usr/share/nginx/html/index.html.backup &&
          nginx -g 'daemon off;' &&
          while true; do
            inotifywait -e modify /usr/share/nginx/html/index.html &&
            cp /usr/share/nginx/html/index.html /usr/share/nginx/html/index.html.backup &&
            echo "ConfigMap updated and reloaded at $(date)";
          done;
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-html-config
