apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - guestbook-deployment.yaml
  - guestbook-svc.yaml
configMapGenerator:
  - name: nginx-html
    files:
      - index.html
generatorOptions:
  disableNameSuffixHash: true